version: '3.9'

services: 
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        container_name: es01
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"            
            discovery.type: single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
        - type: volume
          source: es01
          target: /usr/share/elasticsearch/data
        ports:
            - 9200:9200
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200"]'

    nginx:
        image: max/nginx ## change image
        ports: 
            - 80:80
    
volumes:
  es01:        
        